---

/control_system:
  ros__parameters:
    ###
    # Robot
    ###
    ip: "192.168.1.10"
    latency_warn: 10000
    latency_error: 20000

    dual_arm: true
    robot_id: 2

    is_gripper_open: false 

    model_path: "./models/urdf/gen3_2f85_fixed.urdf"
    # model_path: "./models/urdf/gen3_2f85_dumbbell_1lb.urdf"

    ros_traj_topic: "trajectory_2"
    ros_traj_enb: false
    debug: false

    # motor dynamics parameters
    friction: [0.5217383101288284, 0.5769579059927288, 0.4213397946418778, 0.4945515376566732, 0.1611070502661354, 0.1333491185514130, 0.1434440181717370]
    damping: [10.5, 7.4064845817230722, 9.9727633408172860, 8.2667950822503915, 8.8572249026528151, 8.7110831569332845, 8.8881903638306934]
    transmissionInertia: [8.03, 11.9962024615303644, 9.0025427861751517, 11.5806439316706360, 8.4665040917914123, 8.8537069373742430, 8.8587303664685315]
    offset: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    # friction: [0.0784056716873517,0.3555204729200747,0.3952344013937682,0.4534811633402858,0.09301031196704765,0.116913366972135,0.1995427228470504]
    # damping: [11.31528137441497,13.08049291337487,10.84215579520015,11.59371952140681,9.804089812006776,10.62301568718394,9.610056515230077]
    # transmissionInertia: [7.485353847104333, 7.320681749988109,7.846123679930462,7.528515178510875,7.42767630853946,7.380517931078489,7.7248481008135]
    # offset: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    # friction: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    # damping: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    # transmissionInertia: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
    # offset: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    
    # model uncertainty parameters
    friction_eps: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
    damping_eps: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
    transmissionInertia_eps: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
    mass_eps: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
    com_eps: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
    inertia_eps: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]

    ###
    # PARAMS
    ###
    # controllers
    controller_type: "GRAV_PID" # PID, GRAV_PID, ARMOUR

    # PID
    # Kp: [120.0, 200.0, 120.0, 120.0, 120.0, 20.0, 20.0]
    # Ki: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    # Kd: [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]
    Kp: [75.0, 75.0, 75.0, 75.0, 20.0, 20.0, 20.0]
    Ki: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    Kd: [5.0, 5.0, 5.0, 5.0, 1.0, 1.0, 1.0]

      # passivity-based controller parameters
    Kr: [5.0, 5.0, 5.0, 5.0, 7.0, 7.0, 7.0]

      # Armour robust controller parameters
    alpha: 20.0
    V_max: 2e-2
    r_norm_threshold: 1e-8

      # Althoff robust controller parameters
    phi_p: 30.
    phi_i: 0.1
    kappa_p: 20.0
    kappa_i: 2.0
    max_error: 1.

    has_init_pos: false
    # init_pos: [3.75, -1.0472, 0., -2.0944, 0., 1.5708, 0.]
    
    # crows trajectory 2 - left cubby
    # init_pos: [-0.5235983069999999, 0.867848, 0.41687200000000013, 0.823132, -1.115998307, -0.090635307, -0.755029307]
    # crows trajectory 3 - 
    # init_pos: [-1.801721307,1.298542,0.36102100000000004,0.581369,-0.4001693070000001,-0.188059307,-1.517005307]
    # crows trajectory 4 - 
    # init_pos: [-1.747458307, 1.844359, 0.1986880000000002, 0.378544, -0.36034030699999997, -0.561594307, -1.458065307]
    # crows trajectory 6 - straight up

    # sysid start position
    # init_pos: [1.001089876408351, 0.09140272042061115,  -1.648806446891836,   2.381092213417765,   1.822374826812066,  0.1466609489107418, 0.9315315991321746]

    # init_pos: [0.0, 0.262, 3.142, 4.014, 6.283, 0.960, 1.571] # home position
    init_pos: [0.0, 0.262, 3.142, -2.2692, 0.0, -0.6108, 1.571] # near home position
    # init_pos: [2.1330967, 0.92962713, 2.09719171, -1.57763623, 0.86096777, -1.15192888, 0.89113271] # a pickup position

    # init_pos: [0.3165,    0.9076,    2.9845,    4.6763,    0.2054,    0.9243,    0.0]
    # init_pos: [1.28159142, 0.6, -2.6481, -1.5484, 2.55565072, 0.83405794, 2.05711487]


/ros_kortex_system:
  ros__parameters:
    ip: "192.168.1.10"
    # arm_enb: 0b1111111 # Joints to enable LSB: joint 0